-- sample genres

insert into genre(name)
values
('FANTASY'),
('HISTORICAL_FICTION'),
('SCIENCE_FICTION'),
('HORROR'),
('ROMANCE_NOVEL'),
('MYSTERY'),
('MEMOIR'),
('ADVENTURE_FICTION'),
('CONTEMPORARY_LITERATURE'),
('MAGICAL_REALISM'),
('LITERARY_FICTION'),
('CHILDRENS_LITERATURE'),
('DYSTOPIAN'),
('SUSPENSE'),
('YOUNG_ADULT'),
('GRAPHIC_NOVEL'),
('PARANORMAL_ROMANCE'),
('SHORT_STORY'),
('CLASSIC'),
('COMEDY'),
('DRAMA'),
('HISTORY'),
('THRILLER'),
('CRIME')
